spring.application.name=email-system
spring.datasource.url=jdbc:postgresql://localhost:5432/email_system
spring.datasource.username=postgres
spring.datasource.password=KKepler477

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=v6+Jzx4+ap8YNUhPCaR8ZU93tushtXh6nNCsZK11Qec=